### ISSUE TITLE
Дискошар

### ISSUE THREAD

**Issue by grphil** [Algocode-CMS/algocode#1]
Надо, чтобы при нажатии на самый левый нижний ок в самом правом контесте сверху появлялся дискошар и начинала играть музыка. Важное замечание: если не сдана не одна задача, то дискошар должен появляться снизу после трёхкратного нажатия на самую левую верхнюю.

**Comment by qoo2p5** [comment]
Я считаю, что это лишняя опция.

**Comment by p4vook** [comment]
Но почему?
